### ISSUE TITLE
Question: Proper procedure to upgrade from v1 to v2

### ISSUE THREAD

**Issue by UnKnoWn-Consortium** [postalsys/emailengine#100]
I have a production deployment of emailengine v1. I would like to confirm if there is any particular procedure that has to be taken before properly upgrading to v2. Or can I just download the v2 executable and replace the v1 executable and that's it? Thanks.

**Comment by andris9** [comment]
It should work out of the box though you’d have to go through the configuration pages and double check if everything is correct and update where needed, as some defaults have changed.

**Comment by andris9** [comment]
Oh, almost forgot, there's one major change though - all API requests require authentication. v1 used HTTP basic auth, v2 uses bearer tokens. So you must generate an access token in the admin dashboard and then use it when making requests.

So instead of doing a plain unauthenticated query like was possible in v1
```
curl "http://127.0.0.1:3000/v1/stats"
```

you now have to include the authorization header in v2:

```
curl "http://127.0.0.1:3000/v1/stats" --header "Authorization: Bearer <token>"
```
