### ISSUE TITLE
How to get access token in automated tests?

### ISSUE THREAD

**Issue by steinroe** [postalsys/emailengine#102]
**Is your feature request related to a problem? Please describe.**
As far as I understand, the only way to access the API is using a bearer token. This bearer token is generated in the admin dashboard. In automated tests, it would be great to get an access token without using the UI. 

**Describe the solution you'd like**
Maybe a root api secret that can be used to generate an access token via the API? Or a secret set by an ENV that, if set, allows all requests?

**Describe alternatives you've considered**
Doing it in the UI, but this is not possible in automated testing environments. Or did I miss something here?

**Comment by steinroe** [comment]
Another use case: Automatically injecting the token as env var into the service that interacts with emailengine

**Comment by andris9** [comment]
Seems relevant, I'll look into it and possible solutions

**Comment by andris9** [comment]
I added functionality for EmailEngine where you can provision new access tokens via CLI. You can also export an existing token and then import it to another EmailEngine instance. This way you could create the token once, hard code the actual access token value into your tests, and import the exported token to the new instance.

See the instructions and examples [here](https://emailengine.app/prepared-access-token) (described features are available since v2.2.0)

**Comment by steinroe** [comment]
Thats was fast, thanks! I will give it a try today.

**Comment by steinroe** [comment]
Works like a charm, thanks! Maybe we could add the link to the documentation into the menu on the website so that people can find it?
