### ISSUE TITLE
Webhooks are triggered again at random

### ISSUE THREAD

**Issue by marnickmenting** [postalsys/emailengine#104]
**Describe the bug**
We have 20 accounts connected to EmailEngine right now. Sometimes, about once a week, one account gets flushed with webhooks from e-mails that were old and already processed long ago. It seems it looses its cache and starts sending webhooks from the beginning.

**To Reproduce**
I can't find a pattern. It seems to happen only on a few accounts. Most of them are Office365 accounts. I asked the customers and the e-mails were not moved or flagged.

**Expected behavior**
Sending a webhook only once.

**Screenshots**
Look at the webhook date and the e-mail date.
![CleanShot 2021-12-13 at 19 34 34](https://user-images.githubusercontent.com/10233625/145869427-1cbaaedb-a973-45d6-a026-26caebe28d4e.png)

**Desktop (please complete the following information):**
Chrome on MacOS

**Additional context**
EmailEngine v1.14.1
I can provide log file for the specific account where it happened today.

**Comment by andris9** [comment]
Do you happen to have the `id` or `uid` values for previous versions of these messages stored anywhere? Sometimes, Desktop Outlook plugins download and reupload messages in the background (for example, scanning and managing spam). UID values are immutable, so if anything is downloaded and reuploaded, it looks like a completely new message for EmailEngine. I would suggest using the webhooks from EmailEngine as a "soft" indicator, not anything "transactional." You should keep a list of Message-ID values on your side and match any new messages against that table because, as you pointed out, also copying/moving messages around triggers new email notifications.

**Comment by marnickmenting** [comment]
I do not have the emailengine id of old messages. I do store them now for easier debugging in the future. I will check if the id's change indeed when this sync happens again. Maybe it is indeed some scanning application that is mutating the id's. Thanks!
