### ISSUE TITLE
messageNew triggers only for INBOX if message is moved between folders 

### ISSUE THREAD

**Issue by christianwesthoff** [postalsys/emailengine#123]
**Describe the bug**
If message is moved between folders "messageNew" webhook triggers only if the destination folder is INBOX.

**To Reproduce**
1. Move message from INBOX to e.g. Spam

**Expected behavior**
"messageNew" webhook should also trigger for other folders.

**Comment by andris9** [comment]
EmailEngine checks non-INBOX folders once in 15 minutes. Only INBOX changes are pushed to EmailEngine by the IMAP server. Once EmailEngine syncs that other folder, it should send that `messageNew` webhook. There's an exception though, that's Gmail. In Gmail, the message is not actually moved from one folder to another, but the labels of the message are changed.

If you wait 15 minutes, do you get that `messageNew` webhook or is it never sent?

**Comment by mastermoo** [comment]
Thanks for getting back so quickly!

Indeed, a webhook is sent in the next 15 minutes. Is there a setting to reduce the number to 5 oder 10 minutes? If not, we will probably use polling, especially for the "SENT" folder, where new emails should appear sooner for our customers.

**Comment by andris9** [comment]
There are multiple options you can take.

1. Set a lower `imap.resyncDelay` [option](https://api.emailengine.app/#operation/postV1Account) (defaults to 15min) so that EmailEngine would poll non-INBOX folders more often for changes. The drawback is that it would generate considerable overhead if you have a large number of accounts,
2. If you know that a folder must include a new message, you can use the [message listing API endpoint](https://api.emailengine.app/#operation/getV1AccountAccountMessages) to poll for these new messages
3. If you only care about a few folders and could ignore the others, you could set up separate connections for these folders as described in [this post](https://docs.emailengine.app/measuging-inbox-spam-placement/).

**Comment by mastermoo** [comment]
thank you very much, this really helped 🙏

**Comment by tlonny** [comment]
Hey @andris9 

I just wanted to check a few things about option 2 you described..

1. Does it also pick up deletes?
2. Does it also pick up flag changes?
3. For deletes/flag changes, does it pick up changes for very old e-mails (outside your page window)

I've been testing this out on test mailboxes and it _seems_ like 1 and 2 are true, but just wanted to verify from you before I started properly depending on this behavior...
