### ISSUE TITLE
Node.js api library or Typescript bindings

### ISSUE THREAD

**Issue by archfurry** [postalsys/emailengine#128]
**Is your feature request related to a problem? Please describe.**
Today I got an email with attachments with CID undefined and my script trown Error reading function of undefined
Also I noticed that Google calendar sends a 'application/ics' attachment for meeting but Microsoft Teams email has undocumented text.calendar property of http://127.0.0.1:5678/v1/account/{account}/message/{message} response
Also embedded and inline properties of attachments are not documented and it not very clear how to use them

**Describe the solution you'd like**
I see three possible solutions 

1. Update Swagger documentation regularly
2. Create types library for API responses
3. Create nodejs library with proper types on top of some general purpose http request library like axios

**Additional context**
In my project I have  implemented a subset of Api calls and I could finish the job by making it a separate library

**Comment by andris9** [comment]
In general, you should treat any email message field as optional, even for fields that might seem absolutely required, like the `messageId` field. The email file is a container format with decades of backward compatibility, and you can put pretty much whatever you want into it. Some of it is standardized, and some is proprietary. The sender can set up the message however it likes and only hope for the best that the recipient can actually process all that stuff.

So regarding the CID property, I assume you meant the `contentId` property. Most attachments don't have it set. These are only needed when linking an image from the HTML content to an attachment. So this value can either exist or not. Both cases are valid.

About the undocumented `text/calendar`. There are many `text/*` types. Yet again, some are standardized (`text/html`, `text/plain`, etc.), some are not (`text/watch-html`), pretty much anyone can make up their own if they want to. So the possible properties for the text object is an open list, some possible types are known, some are not. All these are defined as "text" and this is why EmailEngine includes these in the text section and not in the attachments section.

When dealing with email content, you must be able to process unexpected or missing values. The only values that are actually required by the RFC are the `Date` and the `From` headers. Everything else, including `Message-ID` is strictly optional. And even then, not having a `From` header is possible, depending on the MX server if it accepts such a message or not. Not having these fields usually means for the message to go straight to the Spam folder, but you still must be able to process such a message. It's also hard to document all this because how and which fields are set always depends on the sender and it's the final recipient that must figure out how to use that data. Most people usually define a subset of features that they support and ignore everything else. Eg. you can treat all attachments as regular attachments and not try to inline these into the HTML.
