### ISSUE TITLE
Get exact From via "documentStore=true"

### ISSUE THREAD

**Issue by wouafff** [postalsys/emailengine#145]
When searching with an email address : 
/v1/account/account_id/search?page=0&pageSize=200&documentStore=true   
with a body like :
`{
				"search": {
				  "from": "javier@vins.com"
				}
 }`  

it will search for "javier" in name and address fields, instead of the exact string "javier@vins.com", so I will get result from another person as well (with the same firstname "javier")

**Describe the solution you'd like**

If I want to search on a dedicated address email, I want the strict result

Maybe by define directly to the "address" field in the body search:
`{
"search": {
"from": {
"address": "javier@vins.com"
}
}
 }`

**Comment by andris9** [comment]
Yeah, I see the issue. The problem is that the `documentStore` search tries to mimic the IMAP search as much as possible (as it is supposed to work as a cache for it). While IMAP runs that query over the entire From field by doing a substring match, then `documentStore` uses ElasticSearch that does not run a string match but a full-text search against the From header. EmailEngine, mimicking IMAP, also runs the search query against the entire From header. So the final query is not exactly searching for `"javier@vins.com"` but for something like `"javier" or "vins.com"`.

The primary solution I can think of would be to introduce ElasticSearch-specific search query options, as the IMAP search is too vague for this. E.g., there is no "address" search in IMAP, only a "from header" search, and that header can contain a lot of stuff. With ElasticSearch, you could run a keyword query against `from.address` and it would only give exact matches for that specific address.

Here's an example of running an exact match query against the from address directly to ElasticSearch (uses [jq](https://stedolan.github.io/jq/) command for formatting):

```
curl -XPOST -ks "https://localhost:9200/emailengine/_search" \
  -u "elastic:NqDHHrrPVBQtxy9cvIYa" \
  -H "content-type: application/json" \
  -d '{
      "query": {
        "bool": {
          "must": [
            {
              "term": {
                "account": "ekiri"
              }
            },
            {
              "term": {
                "from.address": "andris@postalsys.com"
              }
            }
          ]
        }
      }
    }' | jq .hits.hits
```

and the output would look like this (includes only emails where from address is "andris@postalsys.com"):

```
[
  {
    "_index": "emailengine",
    "_id": "ekiri:AAAADQAABMY",
    "_score": 6.462333,
    "_source": {
      "account": "ekiri",
      "created": "2022-06-15T11:34:35.777Z",
      "path": "INBOX",
      "specialUse": "\\Inbox",
      "id": "AAAADQAABMY",
      "uid": 1222,
      "date": "2020-05-15T08:09:56.000Z",
      "flags": [
        "\\Seen"
      ],
      "size": 3900,
      "subject": "Re: See on proov",
      "from": {
        "name": "Andris Reinman",
        "address": "andris@postalsys.com"
      },
...
````

**Comment by andris9** [comment]
Well, as soon as I wrote that answer, I figured that I could just change the default operator from `"or"` to `"and"` so that ElasticSearch would look for `"javier" and "vins.com"` instead of `"javier" or "vins.com"` and it would already make way better results 🤷‍♂️ I'll add this to the next release.
