### ISSUE TITLE
Attachments update

### ISSUE THREAD

**Issue by edeuxk** [postalsys/emailengine#166]
**Is your feature request related to a problem? Please describe.**
We want to pass an url to attachments without having to download the url before, verify the extension and send the right data.

**Describe the solution you'd like**
I see you use nodemailer in package.json, I'm wondering if you can update your code to support URL like Nodemailer -> https://nodemailer.com/message/attachments/

**Additional context**
![image](https://user-images.githubusercontent.com/8247995/179996851-e18066ad-591e-4bff-bdfa-0d952d912acf.png)

**Comment by andris9** [comment]
This limitation is due to security reasons. EmailEngine usually runs on a different server than the client issuing the API calls, and allowing to use of local files or URLs would open potential security issues. For example, the client could request attachments like this:

```
"attachments": [{
  "path": "/etc/passwd"
}, {
  "path": "http://127.0.0.1:2812/monit/admin"
}]
```

Nodemailer is a library, so there are no such problems.
