### ISSUE TITLE
Selecting `Send "New Email" notifications for incoming emails only` stops all Outlook webhooks

### ISSUE THREAD

**Issue by Jivings** [postalsys/emailengine#465]
**Describe the bug**

If I select this checkbox: `Send "New Email" notifications for incoming emails only` then I stop getting any Outlook webhooks, new or old.

**To Reproduce**
Check box

**Expected behavior**
I should still get new emails for Outlook

**Screenshots**

![CleanShot 2024-10-26 at 19 13 14@2x](https://github.com/user-attachments/assets/d0d84a7c-e0ec-4a61-894f-3243ed10ff33)

**EmailEngine version**
v2.48.4

**Environment**
Docker

**Comment by andris9** [comment]
I'll have it fixed in next week's release. The problem occurs because, when using the Microsoft Graph API to list folders, the primary inbox's name is localized rather than being `INBOX`. EmailEngine currently expects the folder path to be `INBOX`, causing the check to fail when the names don't match.

**Comment by andris9** [comment]
If you use Docker, then the fix is already available when using the `latest` tag instead of `v2`.

**Comment by Jivings** [comment]
Okay thanks!
