### ISSUE TITLE
Issue in messageNew Webhook. 

### ISSUE THREAD

**Issue by rohittrexglobal** [postalsys/emailengine#479]
There is an issue with the Webhook used to receive new emails i.e messageNew. When we receive an email which basically is a reply to another email. We are receiving the whole thread content of previous emails into the body of response as body_plain and body_html. Is there any way to just receive the body content of current email and not the previous thread replies or the emails.

**Comment by andris9** [comment]
EmailEngine returns the HTML and plaintext parts of the email. The email client that sends the email composes the HTML, which is a full document. If you want to extract only the actual reply part of the HTML, you should use an LLM or some other machine learning option because there is usually no technical indication of where the actual reply starts or ends—for EmailEngine, it is a single full HTML document.
